
#To create a fancy map to visualize global lineage dynamics

#rm(list = ls())

## packages
require(pacman)
pacman::p_load(tidyverse, rgdal, sf, rmapshaper, ggforce, cowplot, patchwork, rnaturalearth,
               ggtext, showtext, rnaturalearthdata)


font_add_google("Pacifico", "pacifico")
font_add_google("Source Sans Pro", "source")
showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)


## load data ##################################

head(mutationData) #from readData.R

#our geographical selction
#africo19<- c("Kenya", "Uganda", "The Gambia")
africo19 <-c("South Africa", "India", "Japan", "South Korea", "Belgium", "France",        
             "Germany", "Italy",  "Netherlands", "Norway", "Spain",  "Sweden",        
             "Switzerland", "United Kingdom", "Canada","Mexico", "United States", "Australia",     
              "Brazil")


selectData<- mutationData %>%
  dplyr::filter(
    country %in% africo19
  )

table(selectData$country)

#Top X (5 in this case) lineages per continent
vocs<-c("Alpha", "Beta", "Gamma", "Delta")

summ_lineages<- selectData %>%
  na.omit() %>%
  group_by(country, lineage) %>%
  dplyr::summarise(n=n()) %>%
  arrange(desc(n)) %>%
  slice(1:5) 
                        
                          #######add vocs if not in top 5 per country?


topLineages<-unique(summ_lineages$lineage)

#create a custom pallete to fix lineage colours across continents  #############

number_of_colors_needed <- length(africo19)
  #extract qualitative colour palettes from RColorBrewer
qualitative_color_palettes<- brewer.pal.info[brewer.pal.info$category == "qual",]
  #create mash-up of colours
colour_palette <- unlist(mapply(brewer.pal, qualitative_color_palettes$maxcolors, 
                                   rownames(qualitative_color_palettes)))
  #subset to what we need
my_colour_palette<- colour_palette[c(1:18)] 
  #or randomly (will change everytime)
#my_colour_palette<-sample(colour_palette,number_of_colors_needed)


df_topLineages<- selectData %>%
  dplyr::group_by(country, lineage, date14)  %>%
  dplyr::summarise(topTotal=n()) %>%
  subset(lineage %in% topLineages)  #filter based on top


df_biweeklyTotal<-selectData %>%
  drop_na(.)  %>%
  dplyr::group_by(country, date14)  %>%
  dplyr::summarise(allSeqs=n()) %>%
  left_join(df_topLineages,
            by=c("date14", "country"))

df_biweeklyTotal$topLineage_prop <- df_biweeklyTotal$topTotal/df_biweeklyTotal$allSeqs 


## map ##########
#download.file("http://thematicmapping.org/downloads/TM_WORLD_BORDERS_SIMPL-0.3.zip" , destfile="world_shape_file.zip")
#system("unzip world_shape_file.zip")

globe_shp <- st_read(dsn="./mapShapefiles/", layer="TM_WORLD_BORDERS_SIMPL-0.3")
globe <- st_transform(globe_shp, "+init=epsg:4326") 
#globe <- ms_simplify(globe) # Simplify as otherwise is massive

globe$NAME
africo19 %>% sort()
   #check for missing countries in shp file

selectRegions <- globe %>% 
  dplyr::filter(NAME %in% africo19)


no_borders<- globe %>% 
  dplyr::filter(! NAME %in% africo19)
  
ken <- ne_countries(scale = "medium", returnclass = "sf", country = "Kenya")


(map <- ggplot() +
    geom_sf(data = globe, fill = NA) +
    geom_sf(data = no_borders, color = "#FAFAFA", alpha= 1) +
   #geom_sf(data=ibra_regs, fill = "#E1E3D4") +
   geom_sf(data=selectRegions, fill = my_colour_palette)+
   xlab("Longitude") +
   ylab("Latitude") + 
    #xlim(-135, 135)+
    ylim(-55, 80) +
   theme_bw() +
   theme(plot.background = element_blank(),
         panel.background = element_rect(fill = "lightblue1", colour = "powderblue"),
         axis.title = element_blank(),
         axis.text = element_blank(),
         panel.grid = element_blank(),
         axis.ticks = element_blank(),
         panel.border = element_blank())
)

source("regression_country.R", echo = T)


## plots############
plotFunction<-function(selection, na.rm=T) {
  plot1_data<-df_biweeklyTotal %>% 
    dplyr::filter(country == selection,
                  lineage %in% (summ_lineages %>% dplyr::filter(country == selection))$lineage) #ensure only top5 lineages in select country are plotted
  # plot2_data<- df_country_filtered %>%         # df_country_filtered is generated by `regression_country.R`
  #   dplyr::filter(country==selection)  
  # highestCasesInADay<-max(plot2_data$smoothed_cases_per_million) # we will use this to adjust secondary axis
  
  ggplot() + 
    geom_bar(data=plot1_data, aes(x = date14, y=topLineage_prop,fill=lineage), #fill=forcats::fct_rev(topLineages) #to reverse order
             position = "stack", stat="identity", width=14,color='black')+
    #geom_line(data=plot2_data, aes(x=date, y=smoothed_cases_per_million/highestCasesInADay), size=1)+
    theme_classic() + theme_bw() +
    ylab('Proportion') +
    scale_y_continuous(breaks = c(0,0.2, 0.4,0.6, 0.8, 1))+ #,
                       #labels = scales::comma,
                       #sec.axis = sec_axis(~.*highestCasesInADay, name = "Cases", labels = scales::number))+
    theme(legend.position = "right") +
    scale_x_date(date_labels = "%b \n %Y",date_breaks = "6 months", limits = as.Date(c('2019-12-01','2021-10-01')))+
    theme(axis.title.x = element_blank(),
          axis.title.y = element_text(color="black", size=4,margin = margin(t = 0, r = 0, b = 0, l = 0)),
          axis.text = element_text(color="black", size=4, margin = margin(t = 0, r = 0, b = 0, l = 0)),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          plot.title = element_text(size = 6),
          axis.ticks.length = unit(0.3, "mm"),
         # axis.text = element_text(vjust = 1), ## decrease vertical space
          legend.margin = margin(0,0,0,0),
          legend.background = element_rect(fill = "transparent"),
          legend.box.margin = margin(-10,-10,-10,-10),
          legend.key.height = unit(2.5, "mm"),
          legend.key.width =  unit(1, "mm"),
          legend.text = element_text(size = 4),
          legend.title = element_text(size = 4))+ 
    scale_fill_brewer(palette ="Set3")+
    guides(fill=guide_legend(title=NULL,override.aes = list(size = 0.2)))+
    #guides()+  #reduce size of legend boxes
    ggtitle(selection)
}


# map 1 ####
# lineage dynamics
(Australia <- plotFunction("Australia"))
(Belgium <- plotFunction("Belgium"))
(Brazil <- plotFunction("Brazil"))
(Canada <- plotFunction("Canada"))
(France <- plotFunction("France"))
(Germany <- plotFunction("Germany"))
(India <- plotFunction("India"))
(Italy <- plotFunction("Italy"))
(Japan <- plotFunction("Japan"))
(Mexico <- plotFunction("Mexico"))
(Netherlands <- plotFunction("Netherlands"))
(Norway <- plotFunction("Norway"))
(South_Africa <- plotFunction("South Africa"))
(South_Korea <- plotFunction("South Korea"))
(Spain <- plotFunction("Spain"))
(Sweden <- plotFunction("Sweden"))
(Switzerland <- plotFunction("Switzerland"))
(United_Kingdom <- plotFunction("United Kingdom"))
(United_States <- plotFunction("United States"))


my_colour_palette
selectRegions$NAME

# bring map together
map1 <- ggdraw(xlim = c(2, 58), ylim = c(15,45)) +
  draw_plot(map, x = 0, y = 0, width = 60, height = 60) +
  geom_polygon(aes(x = c(51,50,54.5), y = c(24.5, 27.2, 27.2)),
               fill = "#7FC97F", alpha = 0.6) +
  draw_plot(Australia, x = 50, y = 27, width = 4.5, height = 2.5) +    #Australia
  geom_polygon(aes(x = c(23,23,27.5), y = c(27, 23.5, 23.5)),
               fill = "#BEAED4", alpha = 0.6) +
  draw_plot(Brazil, x = 23, y = 21, width = 4.5, height = 2.5) +     #Brazil
  geom_polygon(aes(x = c(17,15,19.5), y = c(35.7, 37, 37)),
               fill = "#FDC086", alpha = 0.6) +
  draw_plot(Canada, x = 15, y = 37, width = 4.5, height = 2.5) +         #Canada
  geom_polygon(aes(x = c(30.5,30.5,29), y = c(35, 32, 32)),
               fill = "#FFFF99", alpha = 0.6) +
  draw_plot(France, x = 26, y = 29.5, width = 4.5, height = 2.5) +      #France
  geom_polygon(aes(x = c(31.5,34,34), y = c(35.5, 37.2, 34.7)),       
               fill = "#386CB0", alpha = 0.6) +
  draw_plot(Germany, x = 34, y = 34.7, width = 4.5, height = 2.5) +    #Germany
  geom_polygon(aes(x = c(42,41.5,46), y = c(32, 33.5, 33.5)),            
               fill = "#F0027F", alpha = 0.6) +
  draw_plot(India, x = 41.5, y = 33.5,width = 4.5, height = 2.5) +     #India 
  geom_polygon(aes(x = c(31.5,35,35), y = c(34.7, 33, 34.5)),
               fill = "#BF5B17", alpha = 0.6) +
  draw_plot(Italy, x = 35, y = 32, width = 4.5, height = 2.5) +         #Italy
  geom_polygon(aes(c(51,50,54.5), y = c(33.5, 35, 35)),
               fill = "#666666", alpha = 0.6) +
  draw_plot(Japan, x = 50, y = 35, width = 4.5, height = 2.5)+       #Japan  
  geom_polygon(aes(x = c(14.5,11,15.5), y = c(31.5, 29.5, 29.5)),       
               fill = "#1B9E77", alpha = 0.6) +
  draw_plot(Mexico, x = 11, y = 27, width = 4.5, height = 2.5) +    #Mexico
  # geom_polygon(aes(x = c(30.6,31,32.5), y = c(35.5, 31.5, 31.5)),
  #              fill = "#D95F02", alpha = 0.6) +
  # draw_plot(Belgium, x = 31, y = 29, width = 4.5, height = 2.5) +     #Belgium
  geom_polygon(aes(x = c(30.8,26.5,26.5), y = c(35.6, 33, 35.5)),
               fill = "#7570B3", alpha = 0.6) +
  draw_plot(Netherlands, x = 22, y = 33, width = 4.5, height = 2.5) +         #Netherlands
  geom_polygon(aes(x=c(31.8,27.5,32), y = c(37, 37.5,37.5)),
               fill = "#E7298A", alpha = 0.6) +
  draw_plot(Norway, x = 27.5, y = 37.5, width = 4.5, height = 2.5) +        #Norway 
  geom_polygon(aes(x = c(34,33,37.5), y = c(24, 23, 23)),       
               fill = "#66A61E", alpha = 0.6) +
  draw_plot(South_Africa,  x = 33, y = 20.5, width = 4.5, height = 2.5) +    #South Africa
  geom_polygon(aes(x = c(29.5, 25.5, 24), y = c(34, 32, 32)),            
               fill = "#E6AB02", alpha = 0.6) +
  draw_plot(Spain, x = 21, y = 29.5,width = 4.5, height = 2.5) +     #Spain 
  geom_polygon(aes(x=c(32.5,34,34), y = c(37.5, 37.5,40)),
               fill = "#A6761D", alpha = 0.6) +
  draw_plot(Sweden, x = 34, y = 37.5, width = 4.5, height = 2.5) +        #Sweden
  geom_polygon(aes(x = c(31.2,36,36), y = c(35, 30, 31.5)),
               fill = "#666666", alpha = 0.6) +
  draw_plot(Switzerland, x = 36, y = 29, width = 4.5, height = 2.5)  +      #Switzerland

  #moving Belgium after Switzerland to avoid Switzerland polygon positioning itself on top of Belgium graph
  geom_polygon(aes(x = c(30.6,31,32.5), y = c(35.5, 31.5, 31.5)),
               fill = "#D95F02", alpha = 0.6) +
  draw_plot(Belgium, x = 31, y = 29, width = 4.5, height = 2.5) +     #Belgium
  
  geom_polygon(aes(x = c(29.9,26.5,26.5), y = c(36, 36, 38.5)),
               fill = "#A6CEE3", alpha = 0.6) +
  draw_plot(United_Kingdom, x = 22, y = 36, width = 4.5, height = 2.5) +         #United Kingdom
  geom_polygon(aes(x = c(14,10.5,10.5), y = c(35, 33.5, 31)),
               fill = "#1F78B4", alpha = 0.6) +
  draw_plot(United_States, x = 6, y = 31, width = 4.5, height = 2.5)       #United States


pdf(paste0("./figures/Supplementary_Figure_2.pdf"), width=22, height = 13)
map1
dev.off()

# map 2 ####
# fitted linear models

(Australia <- fitAndPlotFunction("Australia"))
(Belgium <- fitAndPlotFunction("Belgium"))
(Brazil <- fitAndPlotFunction("Brazil"))
(Canada <- fitAndPlotFunction("Canada"))
(France <- fitAndPlotFunction("France"))
(Germany <- fitAndPlotFunction("Germany"))
(India <- fitAndPlotFunction("India"))
(Italy <- fitAndPlotFunction("Italy"))
(Japan <- fitAndPlotFunction("Japan"))
(Mexico <- fitAndPlotFunction("Mexico"))
(Netherlands <- fitAndPlotFunction("Netherlands"))
(Norway <- fitAndPlotFunction("Norway"))
(South_Africa <- fitAndPlotFunction("South Africa"))
(South_Korea <- fitAndPlotFunction("South Korea"))
(Spain <- fitAndPlotFunction("Spain"))
(Sweden <- fitAndPlotFunction("Sweden"))
(Switzerland <- fitAndPlotFunction("Switzerland"))
(United_Kingdom <- fitAndPlotFunction("United Kingdom"))
(United_States <- fitAndPlotFunction("United States"))


my_colour_palette
selectRegions$NAME

# bring map together
maps_2 <- ggdraw(xlim = c(2, 58), ylim = c(15,45)) +
  draw_plot(map, x = 0, y = 0, width = 60, height = 60) +
  # draw_line(x = c(20,20,20),y = c(15, 20,25)) +  # yaxis   #the lines are just to help me navigate the map below.
  # draw_line(x = c(2,20,40),y = c(20, 20,20)) +    #xaxis
  geom_polygon(aes(x = c(51,50,53.5), y = c(24.5, 27.2, 27.2)),
               fill = "#7FC97F", alpha = 0.6) +
  draw_plot(Australia, x = 50, y = 27, width = 3.5, height = 2.5) +    #Australia
  geom_polygon(aes(x = c(23,23,26.5), y = c(27, 23.5, 23.5)),
               fill = "#BEAED4", alpha = 0.6) +
  draw_plot(Brazil, x = 23, y = 21, width = 3.5, height = 2.5) +     #Brazil
  geom_polygon(aes(x = c(17,15,18.5), y = c(35.7, 37, 37)),
               fill = "#FDC086", alpha = 0.6) +
  draw_plot(Canada, x = 15, y = 37, width = 3.5, height = 2.5) +         #Canada
  geom_polygon(aes(x = c(30.5,30.5,29), y = c(35, 32, 32)),
               fill = "#FFFF99", alpha = 0.6) +
  draw_plot(France, x = 27, y = 29.5, width = 3.5, height = 2.5) +      #France
  geom_polygon(aes(x = c(31.5,34,34), y = c(35.5, 37.2, 34.7)),       
               fill = "#386CB0", alpha = 0.6) +
  draw_plot(Germany, x = 34, y = 34.7, width = 3.5, height = 2.5) +    #Germany
  geom_polygon(aes(x = c(42,41.5,45), y = c(32, 33.5, 33.5)),            
               fill = "#F0027F", alpha = 0.6) +
  draw_plot(India, x = 41.5, y = 33.5,width = 3.5, height = 2.5) +     #India 
  geom_polygon(aes(x = c(31.5,35,35), y = c(34.7, 32, 34.5)),
               fill = "#BF5B17", alpha = 0.6) +
  draw_plot(Italy, x = 35, y = 32, width = 3.5, height = 2.5) +         #Italy
  geom_polygon(aes(c(51,50,53.5), y = c(33.5, 35, 35)),
               fill = "#666666", alpha = 0.6) +
  draw_plot(Japan, x = 50, y = 35, width = 3.5, height = 2.5)+       #Japan  
  geom_polygon(aes(x = c(14.5,11,14.5), y = c(31.5, 29.5, 29.5)),       
               fill = "#1B9E77", alpha = 0.6) +
  draw_plot(Mexico, x = 11, y = 27, width = 3.5, height = 2.5) +    #Mexico
  # geom_polygon(aes(x = c(30.6,31,32.5), y = c(35.5, 31.5, 31.5)),
  #              fill = "#D95F02", alpha = 0.6) +
  # draw_plot(Belgium, x = 31, y = 29, width = 3.5, height = 2.5) +     #Belgium
  geom_polygon(aes(x = c(30.8,25.5,25.5), y = c(35.6, 32.5, 35)),
               fill = "#7570B3", alpha = 0.6) +
  draw_plot(Netherlands, x = 22, y = 32.5, width = 3.5, height = 2.5) +         #Netherlands
  geom_polygon(aes(x=c(31.8,28,31.5), y = c(37, 37.5,37.5)),
               fill = "#E7298A", alpha = 0.6) +
  draw_plot(Norway, x = 28, y = 37.5, width = 3.5, height = 2.5) +        #Norway 
  geom_polygon(aes(x = c(34,33,36.5), y = c(24, 23, 23)),       
               fill = "#66A61E", alpha = 0.6) +
  draw_plot(South_Africa,  x = 33, y = 20.5, width = 3.5, height = 2.5) +    #South Africa
  geom_polygon(aes(x = c(29.5, 26.5, 25), y = c(34, 32, 32)),            
               fill = "#E6AB02", alpha = 0.6) +
  draw_plot(Spain, x = 23, y = 29.5,width = 3.5, height = 2.5) +     #Spain 
  geom_polygon(aes(x=c(32.5,34,34), y = c(37.5, 37.5,40)),
               fill = "#A6761D", alpha = 0.6) +
  draw_plot(Sweden, x = 34, y = 37.5, width = 3.5, height = 2.5) +        #Sweden
  geom_polygon(aes(x = c(31.2,35,35), y = c(35, 30, 31.5)),
             fill = "#666666", alpha = 0.6) +
  draw_plot(Switzerland, x = 35, y = 29, width = 3.5, height = 2.5)  +      #Switzerland
  
  geom_polygon(aes(x = c(30.6,31,32.5), y = c(35.5, 31.5, 31.5)),
               fill = "#D95F02", alpha = 0.6) +
  draw_plot(Belgium, x = 31, y = 29, width = 3.5, height = 2.5) +     #Belgium
  
  geom_polygon(aes(x = c(29.9,25.5,25.5), y = c(36, 36, 38.5)),
               fill = "#A6CEE3", alpha = 0.6) +
  draw_plot(United_Kingdom, x = 22, y = 36, width = 3.5, height = 2.5) +         #United Kingdom
  geom_polygon(aes(x = c(14,10.5,10.5), y = c(35, 33.5, 31)),
               fill = "#1F78B4", alpha = 0.6) +
  draw_plot(United_States, x = 7, y = 31, width = 3.5, height = 2.5)       #United States

#yeay
#if it works, dont touch it
    
pdf(paste0("./figures/Supplementary_Figure_3.pdf"), width=22, height = 13)
maps_2
dev.off()




##################
###merged (inset plots)


Australia <- plotFunction("Australia") + 
  inset_element(fitAndPlotFunction("Australia"), left = 0.0,right = 0.3, bottom = 0.63, top = 0.985)

Belgium<-plotFunction("Belgium") +
  inset_element(fitAndPlotFunction("Belgium"), left = 0.0,right = 0.45, bottom = 0.62, top = 0.985)

Brazil<-plotFunction("Brazil") + 
  inset_element(fitAndPlotFunction("Brazil"), left = 0.0,right = 0.33, bottom = 0.7, top = 0.985)

Canada<-plotFunction("Canada") +
  inset_element(fitAndPlotFunction("Canada"), left = 0.0,right = 0.45, bottom = 0.6, top = 0.985)

France<-plotFunction("France") + 
  inset_element(fitAndPlotFunction("France"), left = 0.15,right = 0.5, bottom = 0.74, top = 0.985)

Germany<-plotFunction("Germany") + 
  inset_element(fitAndPlotFunction("Germany"), left = 0.1,right = 0.5, bottom = 0.6, top = 0.985)

India<-plotFunction("India") + 
  inset_element(fitAndPlotFunction("India"), left = 0.16,right = 0.61, bottom = 0.6, top = 0.985)

Italy<-plotFunction("Italy") + 
  inset_element(fitAndPlotFunction("Italy"), left = 0.0,right = 0.41, bottom = 0.6, top = 0.985)

Japan<-plotFunction("Japan") + 
  inset_element(fitAndPlotFunction("Japan"), left = 0.0,right = 0.33, bottom = 0.65, top = 0.985)

Mexico<-plotFunction("Mexico") + 
  inset_element(fitAndPlotFunction("Mexico"), left = 0.0,right = 0.43, bottom = 0.6, top = 0.985)

Netherlands<-plotFunction("Netherlands") + 
  inset_element(fitAndPlotFunction("Netherlands"), left = 0.05,right = 0.5, bottom = 0.6, top = 0.985)

Norway<-plotFunction("Norway") +
  inset_element(fitAndPlotFunction("Norway"),left = 0.285,right = 0.623, bottom = 0.6, top = 0.985)

South_Africa<-plotFunction("South Africa") + 
  inset_element(fitAndPlotFunction("South Africa"), left = 0.09,right = 0.49, bottom = 0.6, top = 0.985)

#South_Korea<-fitAndPlotFunction("South Korea")

Spain<-plotFunction("Spain") + 
  inset_element(fitAndPlotFunction("Spain"), left = 0.0,right = 0.4, bottom = 0.65, top = 0.985)

Sweden<-plotFunction("Sweden") +
  inset_element(fitAndPlotFunction("Sweden"), left = 0.0,right = 0.5, bottom = 0.6, top = 0.985)

Switzerland<-plotFunction("Switzerland") + 
  inset_element(fitAndPlotFunction("Switzerland"), left = 0.12,right = 0.48, bottom = 0.6, top = 0.985)

United_Kingdom<-plotFunction("United Kingdom") + 
  inset_element(fitAndPlotFunction("United Kingdom"), left = 0.0,right = 0.4, bottom = 0.55, top = 0.985)

United_States<-plotFunction("United States") + 
  inset_element(fitAndPlotFunction("United States"), left = 0.0,right = 0.5, bottom = 0.55, top = 0.985)

# bring map together
maps_2 <- ggdraw(xlim = c(2, 58), ylim = c(15,45)) +
  draw_plot(map, x = 0, y = 0, width = 60, height = 60) +
  # draw_line(x = c(20,20,20),y = c(15, 20,25)) +  # yaxis   #the lines are just to help me navigate the map below.
  # draw_line(x = c(2,20,40),y = c(20, 20,20)) +    #xaxis
  geom_polygon(aes(x = c(51,50,53), y = c(25.5, 27.2, 27.2)),
               fill = "#7FC97F", alpha = 0.6) +
  draw_plot(Australia, x = 49, y = 27, width = 4.5, height = 3) +    #Australia
  geom_polygon(aes(x = c(15,16.8,16.8), y = c(19, 19.6, 18.4)),
               fill = "#BEAED4", alpha = 0.6) +
  draw_plot(Brazil, x = 16.7, y = 18.35, width = 6, height = 3) +     #Brazil
  geom_polygon(aes(x = c(11.4,10,12), y = c(21.9, 22.5, 22.5)),
               fill = "#FDC086", alpha = 0.6) +
  draw_plot(Canada, x = 9.5, y = 22, width = 6, height = 3) +         #Canada
  geom_polygon(aes(x = c(20.5,20,20.8), y = c(21.9, 20.8, 20.8)),
               fill = "#FFFF99", alpha = 0.6) +
  draw_plot(France, x = 19, y = 19.7, width = 6, height = 3) +      #France
  geom_polygon(aes(x = c(34.2,33.2,36.1), y = c(18.7, 19.2, 19.2)),       
               fill = "#386CB0", alpha = 0.6) +
  draw_plot(Germany, x = 33, y = 19.15, width = 3.5, height = 1.3) +    #Germany
  geom_polygon(aes(x = c(15,16.8,16.8), y = c(19, 19.6, 18.4)),            
               fill = "#F0027F", alpha = 0.6) +
  draw_plot(India, x = 16.7, y = 18.35, width = 3.5, height = 1.3) +     #India 
  geom_polygon(aes(x = c(17,13,17.5), y = c(15.2, 16.2, 16.2)),
               fill = "#BF5B17", alpha = 0.6) +
  draw_plot(Italy, x = 20, y = 11.8, width = 3.5, height = 1.3) +         #Italy
  geom_polygon(aes(x = c(51,50,53), y = c(35.5, 37.2, 37.2)),
               fill = "#666666", alpha = 0.6) +
  draw_plot(Japan, x = 12.5, y = 16.2, width = 3.5, height = 1.3)        #Japan  
